### ISSUE TITLE
Question: How to include default / reserved attributes in the log message?

### ISSUE THREAD

**Issue by meitham** [jteppinette/python-logfmter#4]
Thank you for making this library available.  I have been looking at the tests and docs but could not find out how I can include some of the keys you defined as "RESERVED" in my message, such as ``asctime``.   I would like to say::

```
>>> logger.info("hello")
"asctime=2022-04-20 msg='hello'"
```

without having to pass ``asctime`` in as an ``extra``.  I have tried the below in my dictconfig but did not work::

```
        'logfmt': {
            'format': 'on=%(asctime)s level=%(levelname)s module=%(name)s msg=%(message)s',
            'class': 'logfmter.Logfmter',
        },
```

 Is this possible?

**Comment by jteppinette** [comment]
This functionality has been added by the latest 0.0.5 release.

Thank you for using the library and providing this support!

Please consider starring or becoming a sponsor of the project to help continue development!

---

**Default Keys**

You can request that the formatter always include certain attributes on the
log record by using the `keys` parameter. If the key you want to include in
your output is represented by a different attribute on the log record, then
you can use the `mapping` parameter to provide that key/attribute mapping.

_Notice, the `keys` parameter defaults to `["at"]` and will be overridden
by any provided `keys`._

```python
import logging
from logfmter import Logfmter

formatter = Logfmter(keys=["at", "processName"])

handler = logging.StreamHandler()
handler.setFormatter(formatter)

logging.basicConfig(handlers=[handler])

logging.error("hello") # at=ERROR processName=MainProceess msg=hello
```

_Utilizing a mapping to convert the `processName` attribute to `process`._

_Notice, the `mapping` parameter defaults to `{"at": "levelname"}` and will be overridden
by any provided `mapping`._

```python
import logging
from logfmter import Logfmter

formatter = Logfmter(
    keys=["at", "process"],
    mapping={"at": "levelname", "process": "processName"}
)

handler = logging.StreamHandler()
handler.setFormatter(formatter)

logging.basicConfig(handlers=[handler])

logging.error("hello") # at=ERROR process=MainProceess msg=hello
```

**Date Formatting**

If you request the `asctime` attribute (directly or through a mapping), then the date format
can be overridden through the `datefmt` parameter.

```python
import logging
from logfmter import Logfmter

formatter = Logfmter(
    keys=["at", "when"],
    mapping={"at": "levelname", "when": "asctime"},
    datefmt="%Y-%m-%d"
)

handler = logging.StreamHandler()
handler.setFormatter(formatter)

logging.basicConfig(handlers=[handler])

logging.error("hello") # at=ERROR when=2022-04-20 msg=hello
```

**Comment by jteppinette** [comment]
@meitham Let me know if this resolves your question, then I will close this issue.

**Comment by meitham** [comment]
@jteppinette Very kind of you to have this feature added at such a short notice, much appreciated.

It does indeed solve my issue, thank you very much.
